Create storage location when it doesn't exist
The method `getorCreateLocation` was only looking for existing storage
locations with a matching name but never created one. This leads to the
following error if a storage location doesn't exist yet:

    Traceback (most recent call last):
      File "migratePKCategories.py", line 132, in <module>
        'location' : itloc.pk
    AttributeError: 'int' object has no attribute 'pk'

With this change the storage location is created if it doesn't exist yet
in InventTree.